### ISSUE TITLE
First-time GPLv3 violation notice of rseichter/automx2

### ISSUE THREAD

**Issue by rseichter** [HLFH/automua#2]
@HLFH This is not how a "fork" works. You took my existing repository https://github.com/rseichter/automx2 and modified the copyright notes, replacing my name with yours. That is a ripoff of my original work and just won't do. Please delete your Git repository ASAP.

**Comment by HLFH** [comment]
You have not read my commits. I have the copyrights on my commits/changes and you have them on yours. There were many contributors of automx, at least two visible on automx2... For automua, you can see the git history with the list of contributors: https://github.com/HLFH/automua/commits/master. And GitHub shows the contributors. 
<img width="349" alt="Screenshot 2022-10-28 at 19 21 47" src="https://user-images.githubusercontent.com/2359059/198706830-42704417-b9b3-4c38-9ec5-d0517a900fc0.png">

I will now check what to fix about the copyright notices.

**Comment by rseichter** [comment]
You don't have the copyright for changes made to my code. That is not how the Gnu Public License works. I own the complete Git repository, every file and piece of code you "forked" and if you make any changes, I still own these file just like before. Hence, what you did is a clear licensing violation and changing the copyright notices is theft of intellectual propaerty. I am not saying you did it on purpose, mind you, but that does not change the facts. As far as contributors go, there was nobody but me and Patrick, who only provided early drafts of documentation and no source code whatsoever. automx2 is mine and nobody else's intellectual property, it has been mine since way back to the initial commit in 2019. If you want the copyright, you need to write your own software from scratch, without using a single line of other people's code.

**Comment by HLFH** [comment]
I have read your comments: https://github.com/HLFH/automua/blob/master/README.md.
In the meantime, I cleared the repo in order to review in details the matter.
I'll keep you posted.

**Comment by HLFH** [comment]
@rseichter You can review the repo (https://github.com/HLFH/automua) and tell me if this still constitutes for you a GPLv3 license violation.

**Comment by rseichter** [comment]
It will take me a while to go through the details (given my current bad health it may take a few days to go through the material in depth, so I'd ask you to please reopen this issue for the time being). What I can see right away is that you added your Copyright notices in some of my files, which is not OK (again, the files remain "mine" even if you change them), and that you detached your repository instead of keeping it flagged as a GitHub fork. Also, you did not include a clearly visible link to my original software in README.

I have no problems with you using automx2 in a personal (!) environment or I would not have made the source code accessible, but if you intend to go public, there must never be any doubt that you are passing along *my* work, with a few minor updates. Trying to pass off my work as yours in any way is obviously not acceptable. I'm pretty certain that you would not take a Mercedes, add a spoiler and some cosmetic changes, and then try to sell it as a "HLFH Special", or would you? 😉

By the way, on a technical note, the changes you made to populate_with_dict() do not really address a bug of automx2, but a quirk of either the particular MySQL driver you used with SQLAlchemy, or possibly of SQLAlchemy itself. Interesting.

```
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(MySQLdb.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`automx2`.`domain`, CONSTRAINT `domain_ibfk_1` FOREIGN KEY (`provider_id`) REFERENCES `provider` (`id`))')

```

**Comment by HLFH** [comment]
Again, I wish you a speedy recovery.

In the last version, I added trademark notices related to the "automua" name and I kept every prominent copyright notice of your work. 

And when a file is modified more than the name change from automx2 to automua, I also added a copyright notice because I consider that changing the code in the file makes it a [shared copyright](https://softwareengineering.stackexchange.com/questions/211365/who-owns-modifications-to-open-source-software).

Detaching a repository instead of keeping it flagged as a GitHub fork does not constitute a license violation.
And I gave you notice as soon as it was published to be sure to fix any mistakes I would have made.
I have seen many forks of various open source projects adopting this strategy.
Forked repositories/projects kept as GitHub forks **are not currently searchable** on GitHub and I find it quite limiting.

> if you intend to go public, there must never be any doubt that you are passing along my work, with a few minor updates

At this stage, you are [Lentulus Batiatus](https://en.wikipedia.org/wiki/Gnaeus_Cornelius_Lentulus_Vatia) and I could be your [Spartacus](https://en.wikipedia.org/wiki/Spartacus). The only intention is a public fork with currently minor changes, and that [directly accepts code contributions](https://www.gnu.org/licenses/gpl-faq.en.html#WhyDoesTheGPLPermitUsersToPublishTheirModifiedVersions). I use a lot Arch Linux on my server and I wanted as well a working package for Arch Linux AUR, which [I have done](https://aur.archlinux.org/packages/automua).

> By the way, on a technical note, the changes you made to populate_with_dict() do not really address a bug of automx2, but a quirk of either the particular MySQL driver you used with SQLAlchemy, or possibly of SQLAlchemy itself. Interesting.

I will look into this.

> You did not include a clearly visible link to my original software in README.

I will also look into it.

**Comment by HLFH** [comment]
@rseichter A link has been added to the README: https://github.com/HLFH/automua/blob/master/README.md

**Comment by HLFH** [comment]
I consider the potential first-time GPLv3 violation is cured prior to 30 days after my receipt of the copyright's holder notice.
As the automx2 copyright's holder, I consider you are the one to determine if the violation is cured or not.
I will close this topic by 28/11/2022, more than 30 days after the notice.

**Comment by HLFH** [comment]
Closing.
